[workspace]
members = [
    'node',
    'pallets/template',
    'runtime',
    'pallets/hello-substrate',
    'pallets/struct-storage',
    'pallets/blx-storage',
    'pallets/double-map',
    'pallets/blx-doublemap',
]
[profile.release]
panic = 'unwind'
